// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return webProd;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions webProd = FirebaseOptions(
    apiKey: 'AIzaSyAMW4GfdgCAMwSNyhLnwLkNeYX3atpJab0',
    appId: '1:12970252530:web:d5ef595244f3f8c9fc986b',
    messagingSenderId: '12970252530',
    projectId: 'pizza-delivery-9b66e',
    authDomain: 'pizza-delivery-9b66e.firebaseapp.com',
    storageBucket: 'pizza-delivery-9b66e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaPaTKUEsUll4QBfXoObbldtdg5vYKHRM',
    appId: '1:12970252530:android:a1f7e639ef032954fc986b',
    messagingSenderId: '12970252530',
    projectId: 'pizza-delivery-9b66e',
    storageBucket: 'pizza-delivery-9b66e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsmjZv5v8679yqWBtSpILxkoZjxxR_5Yo',
    appId: '1:12970252530:ios:0e1e66326514a241fc986b',
    messagingSenderId: '12970252530',
    projectId: 'pizza-delivery-9b66e',
    storageBucket: 'pizza-delivery-9b66e.appspot.com',
    iosBundleId: 'com.example.flutterPizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsmjZv5v8679yqWBtSpILxkoZjxxR_5Yo',
    appId: '1:12970252530:ios:0e1e66326514a241fc986b',
    messagingSenderId: '12970252530',
    projectId: 'pizza-delivery-9b66e',
    storageBucket: 'pizza-delivery-9b66e.appspot.com',
    iosBundleId: 'com.example.flutterPizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMW4GfdgCAMwSNyhLnwLkNeYX3atpJab0',
    appId: '1:12970252530:web:64d36cdd74136430fc986b',
    messagingSenderId: '12970252530',
    projectId: 'pizza-delivery-9b66e',
    authDomain: 'pizza-delivery-9b66e.firebaseapp.com',
    storageBucket: 'pizza-delivery-9b66e.appspot.com',
  );
}
